@startuml generated_profile
rectangle #bisque "Library Loading" as sa0
rectangle #coral "Library Loading" as se0_0
se0_0 .u.> sa0
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=pandas\nfunction=" as mi0_0_0
mi0_0_0 .u.> se0_0
rectangle #pink "import pandas as pd" as i0_0_0_0
i0_0_0_0 .u.> mi0_0_0
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=tensorflow\nfunction=" as mi1_0_0
mi0_0_0 -r-> mi1_0_0
mi1_0_0 .u.> se0_0
rectangle #pink "import tensorflow as tf" as i0_1_0_0
i0_0_0_0 -r-> i0_1_0_0
i0_1_0_0 .u.> mi1_0_0
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=keras\nfunction=models" as mi2_0_0
mi1_0_0 -r-> mi2_0_0
mi2_0_0 .u.> se0_0
rectangle #pink "import keras.models" as i0_2_0_0
i0_1_0_0 -r-> i0_2_0_0
i0_2_0_0 .u.> mi2_0_0
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=tensorflow_model_analysis\nfunction=" as mi3_0_0
mi2_0_0 -r-> mi3_0_0
mi3_0_0 .u.> se0_0
rectangle #pink "import tensorflow_model_analysis as tfma" as i0_3_0_0
i0_2_0_0 -r-> i0_3_0_0
i0_3_0_0 .u.> mi3_0_0
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=google.protobuf\nfunction=text_ format" as mi4_0_0
mi3_0_0 -r-> mi4_0_0
mi4_0_0 .u.> se0_0
rectangle #pink "from google.protobuf import text_format" as i0_4_0_0
i0_3_0_0 -r-> i0_4_0_0
i0_4_0_0 .u.> mi4_0_0
rectangle #cyan "algoFamily=Fairness Remediation\nalgoName=MinDiff\nlibrary=tensorflow_model_remediation\nfunction=min_ diff" as mi5_0_0
mi4_0_0 -r-> mi5_0_0
mi5_0_0 .u.> se0_0
rectangle #pink "from tensorflow_model_remediation import min_diff" as i0_5_0_0
i0_4_0_0 -r-> i0_5_0_0
i0_5_0_0 .u.> mi5_0_0
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=helper\nfunction=*" as mi6_0_0
mi5_0_0 -r-> mi6_0_0
mi6_0_0 .u.> se0_0
rectangle #pink "from helper import *" as i0_6_0_0
i0_5_0_0 -r-> i0_6_0_0
i0_6_0_0 .u.> mi6_0_0
rectangle #bisque "Data Preparation" as sa1
sa0 -r-> sa1
rectangle #coral "Data Loading" as se0_1
se0_0 -r-> se0_1
se0_1 .u.> sa1
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=pandas\nfunction=read_ csv" as mi0_0_1
mi6_0_0 -r-> mi0_0_1
mi0_0_1 .u.> se0_1
rectangle #pink "acs_train_df = pd.read_csv('../out/train_dataset.csv')" as i0_0_0_1
i0_6_0_0 -r-> i0_0_0_1
i0_0_0_1 .u.> mi0_0_1
rectangle #coral "Data Preparation" as se1_1
se0_1 -r-> se1_1
se1_1 .u.> sa1
rectangle #cyan "algoFamily=None\nalgoName=None\nlibrary=tensorflow\nfunction=dataframe_ to_ tf_ batches" as mi0_1_1
mi0_0_1 -r-> mi0_1_1
mi0_1_1 .u.> se1_1
rectangle #pink "acs_train_batches = dataframe_to_tf_batches(acs_train_df)" as i0_0_1_1
i0_0_0_1 -r-> i0_0_1_1
i0_0_1_1 .u.> mi0_1_1
rectangle #coral "Data Loading" as se2_1
se1_1 -r-> se2_1
se2_1 .u.> sa1
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=pandas\nfunction=read_ csv" as mi0_2_1
mi0_1_1 -r-> mi0_2_1
mi0_2_1 .u.> se2_1
rectangle #pink "acs_test_df = pd.read_csv('../out/test_dataset.csv')" as i0_0_2_1
i0_0_1_1 -r-> i0_0_2_1
i0_0_2_1 .u.> mi0_2_1
rectangle #coral "Data Preparation" as se3_1
se2_1 -r-> se3_1
se3_1 .u.> sa1
rectangle #cyan "algoFamily=None\nalgoName=None\nlibrary=tensorflow\nfunction=dataframe_ to_ tf_ batches" as mi0_3_1
mi0_2_1 -r-> mi0_3_1
mi0_3_1 .u.> se3_1
rectangle #pink "acs_test_batches = dataframe_to_tf_batches(acs_test_df)" as i0_0_3_1
i0_0_2_1 -r-> i0_0_3_1
i0_0_3_1 .u.> mi0_3_1
rectangle #bisque "Model Building and Training" as sa2
sa1 -r-> sa2
rectangle #coral "Model Building and Training" as se0_2
se3_1 -r-> se0_2
se0_2 .u.> sa2
rectangle #cyan "algoFamily=None\nalgoName=None\nlibrary=keras\nfunction=load_ model" as mi0_0_2
mi0_3_1 -r-> mi0_0_2
mi0_0_2 .u.> se0_2
rectangle #pink "base_model = keras.models.load_model('../out/model.keras')" as i0_0_0_2
i0_0_3_1 -r-> i0_0_0_2
i0_0_0_2 .u.> mi0_0_2
rectangle #coral "Model Training" as se1_2
se0_2 -r-> se1_2
se1_2 .u.> sa2
rectangle #cyan "algoFamily=None\nalgoName=None\nlibrary=TensorFlow\nfunction=predict" as mi0_1_2
mi0_0_2 -r-> mi0_1_2
mi0_1_2 .u.> se1_2
rectangle #pink "base_model_predictions = base_model.predict(acs_test_batches, batch_size=BATCH_SIZE)" as i0_0_1_2
i0_0_0_2 -r-> i0_0_1_2
i0_0_1_2 .u.> mi0_1_2
rectangle #bisque "Others" as sa3
sa2 -r-> sa3
rectangle #coral "Others" as se0_3
se1_2 -r-> se0_3
se0_3 .u.> sa3
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=\nfunction=" as mi0_0_3
mi0_1_2 -r-> mi0_0_3
mi0_0_3 .u.> se0_3
rectangle #pink "SENSITIVE_ATTRIBUTE_VALUES = {1.0: 'Male', 2.0: 'Female'}" as i0_0_0_3
i0_0_1_2 -r-> i0_0_0_3
i0_0_0_3 .u.> mi0_0_3
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=\nfunction=" as mi1_0_3
mi0_0_3 -r-> mi1_0_3
mi1_0_3 .u.> se0_3
rectangle #pink "SENSITIVE_ATTRIBUTE_KEY = 'SEX'" as i0_1_0_3
i0_0_0_3 -r-> i0_1_0_3
i0_1_0_3 .u.> mi1_0_3
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=\nfunction=" as mi2_0_3
mi1_0_3 -r-> mi2_0_3
mi2_0_3 .u.> se0_3
rectangle #pink "PREDICTION_KEY = 'PRED'" as i0_2_0_3
i0_1_0_3 -r-> i0_2_0_3
i0_2_0_3 .u.> mi2_0_3
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=\nfunction=copy" as mi3_0_3
mi2_0_3 -r-> mi3_0_3
mi3_0_3 .u.> se0_3
rectangle #pink "base_model_analysis = acs_test_df.copy()" as i0_3_0_3
i0_2_0_3 -r-> i0_3_0_3
i0_3_0_3 .u.> mi3_0_3
rectangle #bisque "Feature Engineering" as sa4
sa3 -r-> sa4
rectangle #coral "Feature Engineering" as se0_4
se0_3 -r-> se0_4
se0_4 .u.> sa4
rectangle #cyan "algoFamily=Others\nalgoName=None\nlibrary=pandas\nfunction=replace" as mi0_0_4
mi3_0_3 -r-> mi0_0_4
mi0_0_4 .u.> se0_4
rectangle #pink "base_model_analysis[SENSITIVE_ATTRIBUTE_KEY].replace(SENSITIVE_ATTRIBUTE_VALUES, inplace=True)" as i0_0_0_4
i0_3_0_3 -r-> i0_0_0_4
i0_0_0_4 .u.> mi0_0_4
rectangle #cyan "algoFamily=Others\nalgoName=None\nlibrary=pandas\nfunction=DataFrame" as mi1_0_4
mi0_0_4 -r-> mi1_0_4
mi1_0_4 .u.> se0_4
rectangle #pink "base_model_analysis[PREDICTION_KEY] = base_model_predictions" as i0_1_0_4
i0_0_0_4 -r-> i0_1_0_4
i0_1_0_4 .u.> mi1_0_4
rectangle #bisque "Others" as sa5
sa4 -r-> sa5
rectangle #coral "Others" as se0_5
se0_4 -r-> se0_5
se0_5 .u.> sa5
rectangle #cyan "algoFamily=None\nalgoName=None\nlibrary=None\nfunction=None" as mi0_0_5
mi1_0_4 -r-> mi0_0_5
mi0_0_5 .u.> se0_5
rectangle #pink "eval_config_pbtxt = '\n  model_specs {\n    prediction_key: '%s'\n    label_key: '%s' }\n  metrics_specs {\n    metrics { class_name: 'ExampleCount' }\n    metrics { class_name: 'BinaryAccuracy' }\n    metrics { class_name: 'AUC' }\n    metrics { class_name: 'ConfusionMatrixPlot' }\n    metrics {\n      class_name: 'FairnessIndicators'\n      config: \'{'thresholds': [0.50]}\'\n    }\n  }\n  slicing_specs {\n    feature_keys: '%s'\n  }\n  slicing_specs {}\n' % (PREDICTION_KEY, LABEL_KEY, SENSITIVE_ATTRIBUTE_KEY)" as i0_0_0_5
i0_1_0_4 -r-> i0_0_0_5
i0_0_0_5 .u.> mi0_0_5
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=tensorflow_model_analysis\nfunction=Parse" as mi1_0_5
mi0_0_5 -r-> mi1_0_5
mi1_0_5 .u.> se0_5
rectangle #pink "eval_config = text_format.Parse(eval_config_pbtxt, tfma.EvalConfig())" as i0_1_0_5
i0_0_0_5 -r-> i0_1_0_5
i0_1_0_5 .u.> mi1_0_5
rectangle #bisque "Model Building and Training" as sa6
sa5 -r-> sa6
rectangle #coral "Model Validation and Assembling" as se0_6
se0_5 -r-> se0_6
se0_6 .u.> sa6
rectangle #cyan "algoFamily=Fairness Metrics\nalgoName=Fairness Indicators\nlibrary=TensorFlow Model Analysis (TFMA)\nfunction=analyze_ raw_ data" as mi0_0_6
mi1_0_5 -r-> mi0_0_6
mi0_0_6 .u.> se0_6
rectangle #pink "base_model_eval_result = tfma.analyze_raw_data(base_model_analysis, eval_config)" as i0_0_0_6
i0_1_0_5 -r-> i0_0_0_6
i0_0_0_6 .u.> mi0_0_6
rectangle #bisque "Data Preparation" as sa7
sa6 -r-> sa7
rectangle #coral "Data Preparation" as se0_7
se0_6 -r-> se0_7
se0_7 .u.> sa7
rectangle #cyan "algoFamily=Data Filtering\nalgoName=Filtering\nlibrary=pandas\nfunction=DataFrame.loc" as mi0_0_7
mi0_0_6 -r-> mi0_0_7
mi0_0_7 .u.> se0_7
rectangle #pink "sensitive_group_pos = acs_train_df[(acs_train_df[SENSITIVE_ATTRIBUTE_KEY] == 2.0) & (acs_train_df[LABEL_KEY] == 1)]" as i0_0_0_7
i0_0_0_6 -r-> i0_0_0_7
i0_0_0_7 .u.> mi0_0_7
rectangle #cyan "algoFamily=Data Filtering\nalgoName=Filtering\nlibrary=pandas\nfunction=DataFrame.loc" as mi1_0_7
mi0_0_7 -r-> mi1_0_7
mi1_0_7 .u.> se0_7
rectangle #pink "non_sensitive_group_pos = acs_train_df[(acs_train_df[SENSITIVE_ATTRIBUTE_KEY] == 1.0) & (acs_train_df[LABEL_KEY] == 1)]" as i0_1_0_7
i0_0_0_7 -r-> i0_1_0_7
i0_1_0_7 .u.> mi1_0_7
rectangle #bisque "Visualization" as sa8
sa7 -r-> sa8
rectangle #coral "Visualization" as se0_8
se0_7 -r-> se0_8
se0_8 .u.> sa8
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=Python Standard Library\nfunction=print" as mi0_0_8
mi1_0_7 -r-> mi0_0_8
mi0_0_8 .u.> se0_8
rectangle #pink "print(len(sensitive_group_pos), 'positively labeled sensitive group examples')" as i0_0_0_8
i0_1_0_7 -r-> i0_0_0_8
i0_0_0_8 .u.> mi0_0_8
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=Python Standard Library\nfunction=print" as mi1_0_8
mi0_0_8 -r-> mi1_0_8
mi1_0_8 .u.> se0_8
rectangle #pink "print(len(non_sensitive_group_pos), 'positively labeled non-sensitive group examples')" as i0_1_0_8
i0_0_0_8 -r-> i0_1_0_8
i0_1_0_8 .u.> mi1_0_8
rectangle #bisque "Data Preparation" as sa9
sa8 -r-> sa9
rectangle #coral "Data Preparation" as se0_9
se0_8 -r-> se0_9
se0_9 .u.> sa9
rectangle #cyan "algoFamily=Others\nalgoName=None\nlibrary=None\nfunction=None" as mi0_0_9
mi1_0_8 -r-> mi0_0_9
mi0_0_9 .u.> se0_9
rectangle #pink "MIN_DIFF_BATCH_SIZE = 50" as i0_0_0_9
i0_1_0_8 -r-> i0_0_0_9
i0_0_0_9 .u.> mi0_0_9
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=tensorflow\nfunction=dataframe_ to_ dataset" as mi1_0_9
mi0_0_9 -r-> mi1_0_9
mi1_0_9 .u.> se0_9
rectangle #pink "sensitive_group_ds = dataframe_to_dataset(sensitive_group_pos)" as i0_1_0_9
i0_0_0_9 -r-> i0_1_0_9
i0_1_0_9 .u.> mi1_0_9
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=tensorflow\nfunction=dataframe_ to_ dataset" as mi2_0_9
mi1_0_9 -r-> mi2_0_9
mi2_0_9 .u.> se0_9
rectangle #pink "non_sensitive_group_ds = dataframe_to_dataset(non_sensitive_group_pos)" as i0_2_0_9
i0_1_0_9 -r-> i0_2_0_9
i0_2_0_9 .u.> mi2_0_9
rectangle #coral "Data Sub-sampling and Train-test Splitting" as se1_9
se0_9 -r-> se1_9
se1_9 .u.> sa9
rectangle #cyan "algoFamily=Data Manipulation\nalgoName=Batching\nlibrary=TensorFlow\nfunction=batch" as mi0_1_9
mi2_0_9 -r-> mi0_1_9
mi0_1_9 .u.> se1_9
rectangle #pink "sensitive_group_batches = sensitive_group_ds.batch(MIN_DIFF_BATCH_SIZE, drop_remainder=True)" as i0_0_1_9
i0_2_0_9 -r-> i0_0_1_9
i0_0_1_9 .u.> mi0_1_9
rectangle #cyan "algoFamily=Data Transformation\nalgoName=Batching\nlibrary=TensorFlow\nfunction=batch" as mi1_1_9
mi0_1_9 -r-> mi1_1_9
mi1_1_9 .u.> se1_9
rectangle #pink "non_sensitive_group_batches = non_sensitive_group_ds.batch(MIN_DIFF_BATCH_SIZE, drop_remainder=True)" as i0_1_1_9
i0_0_1_9 -r-> i0_1_1_9
i0_1_1_9 .u.> mi1_1_9
rectangle #coral "Data Preparation" as se2_9
se1_9 -r-> se2_9
se2_9 .u.> sa9
rectangle #cyan "algoFamily=Fairness\nalgoName=MinDiff\nlibrary=tensorflow_model_remediation\nfunction=pack_ min_ diff_ data" as mi0_2_9
mi1_1_9 -r-> mi0_2_9
mi0_2_9 .u.> se2_9
rectangle #pink "acs_train_min_diff_ds = min_diff.keras.utils.pack_min_diff_data(original_dataset=acs_train_batches, sensitive_group_dataset=sensitive_group_batches, nonsensitive_group_dataset=non_sensitive_group_batches)" as i0_0_2_9
i0_1_1_9 -r-> i0_0_2_9
i0_0_2_9 .u.> mi0_2_9
rectangle #bisque "Model Building and Training" as sa10
sa9 -r-> sa10
rectangle #coral "Model Building and Training" as se0_10
se2_9 -r-> se0_10
se0_10 .u.> sa10
rectangle #cyan "algoFamily=Statistical Learning\nalgoName=Minimum Discriminant Analysis (MMD)\nlibrary=tensorflow-model-remediations\nfunction=MinDiffModel" as mi0_0_10
mi0_2_9 -r-> mi0_0_10
mi0_0_10 .u.> se0_10
rectangle #pink "min_diff_model = min_diff.keras.MinDiffModel(original_model=base_model, loss=min_diff.losses.MMDLoss(), loss_weight=1)" as i0_0_0_10
i0_0_2_9 -r-> i0_0_0_10
i0_0_0_10 .u.> mi0_0_10
rectangle #coral "Model Training" as se1_10
se0_10 -r-> se1_10
se1_10 .u.> sa10
rectangle #cyan "algoFamily=Optimization Algorithms\nalgoName=Adam\nlibrary=tensorflow\nfunction=compile" as mi0_1_10
mi0_0_10 -r-> mi0_1_10
mi0_1_10 .u.> se1_10
rectangle #pink "min_diff_model.compile(optimizer='adam', loss=tf.keras.losses.BinaryCrossentropy(from_logits=False), metrics=METRICS)" as i0_0_1_10
i0_0_0_10 -r-> i0_0_1_10
i0_0_1_10 .u.> mi0_1_10
rectangle #bisque "Others" as sa11
sa10 -r-> sa11
rectangle #coral "Others" as se0_11
se1_10 -r-> se0_11
se0_11 .u.> sa11
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=\nfunction=" as mi0_0_11
mi0_1_10 -r-> mi0_0_11
mi0_0_11 .u.> se0_11
rectangle #pink "EPOCHS = 10" as i0_0_0_11
i0_0_1_10 -r-> i0_0_0_11
i0_0_0_11 .u.> mi0_0_11
rectangle #bisque "Model Building and Training" as sa12
sa11 -r-> sa12
rectangle #coral "Model Training" as se0_12
se0_11 -r-> se0_12
se0_12 .u.> sa12
rectangle #cyan "algoFamily=Deep Learning\nalgoName=MinDiff Model Training\nlibrary=tensorflow\nfunction=fit" as mi0_0_12
mi0_0_11 -r-> mi0_0_12
mi0_0_12 .u.> se0_12
rectangle #pink "min_diff_model.fit(acs_train_min_diff_ds, epochs=EPOCHS)" as i0_0_0_12
i0_0_0_11 -r-> i0_0_0_12
i0_0_0_12 .u.> mi0_0_12
rectangle #cyan "algoFamily=Deep Learning\nalgoName=MinDiff Model Evaluation\nlibrary=tensorflow\nfunction=evaluate" as mi1_0_12
mi0_0_12 -r-> mi1_0_12
mi1_0_12 .u.> se0_12
rectangle #pink "evaluation_results = min_diff_model.evaluate(acs_test_batches, batch_size=BATCH_SIZE)" as i0_1_0_12
i0_0_0_12 -r-> i0_1_0_12
i0_1_0_12 .u.> mi1_0_12
rectangle #bisque "Visualization" as sa13
sa12 -r-> sa13
rectangle #coral "Visualization" as se0_13
se0_12 -r-> se0_13
se0_13 .u.> sa13
rectangle #cyan "algoFamily=None\nalgoName=None\nlibrary=None\nfunction=print" as mi0_0_13
mi1_0_12 -r-> mi0_0_13
mi0_0_13 .u.> se0_13
rectangle #pink "print('Training complete. Evaluation results: ', evaluation_results)" as i0_0_0_13
i0_1_0_12 -r-> i0_0_0_13
i0_0_0_13 .u.> mi0_0_13
rectangle #bisque "Model Building and Training" as sa14
sa13 -r-> sa14
rectangle #coral "Model Training" as se0_14
se0_13 -r-> se0_14
se0_14 .u.> sa14
rectangle #cyan "algoFamily=Fairness-aware Machine Learning\nalgoName=MinDiff Model\nlibrary=tensorflow_model_remediation\nfunction=predict" as mi0_0_14
mi0_0_13 -r-> mi0_0_14
mi0_0_14 .u.> se0_14
rectangle #pink "min_diff_model_predictions = min_diff_model.predict(acs_test_batches, batch_size=BATCH_SIZE)" as i0_0_0_14
i0_0_0_13 -r-> i0_0_0_14
i0_0_0_14 .u.> mi0_0_14
rectangle #bisque "Others" as sa15
sa14 -r-> sa15
rectangle #coral "Others" as se0_15
se0_14 -r-> se0_15
se0_15 .u.> sa15
rectangle #cyan "algoFamily=\nalgoName=\nlibrary=\nfunction=" as mi0_0_15
mi0_0_14 -r-> mi0_0_15
mi0_0_15 .u.> se0_15
rectangle #pink "min_diff_model_analysis = acs_test_df.copy()" as i0_0_0_15
i0_0_0_14 -r-> i0_0_0_15
i0_0_0_15 .u.> mi0_0_15
rectangle #bisque "Feature Engineering" as sa16
sa15 -r-> sa16
rectangle #coral "Feature Transformation" as se0_16
se0_15 -r-> se0_16
se0_16 .u.> sa16
rectangle #cyan "algoFamily=Data Manipulation\nalgoName=None\nlibrary=pandas\nfunction=replace" as mi0_0_16
mi0_0_15 -r-> mi0_0_16
mi0_0_16 .u.> se0_16
rectangle #pink "min_diff_model_analysis[SENSITIVE_ATTRIBUTE_KEY].replace(SENSITIVE_ATTRIBUTE_VALUES, inplace=True)" as i0_0_0_16
i0_0_0_15 -r-> i0_0_0_16
i0_0_0_16 .u.> mi0_0_16
rectangle #cyan "algoFamily=Fairness-aware Machine Learning\nalgoName=MinDiff\nlibrary=tensorflow_model_remediation\nfunction=MinDiffModel" as mi1_0_16
mi0_0_16 -r-> mi1_0_16
mi1_0_16 .u.> se0_16
rectangle #pink "min_diff_model_analysis[PREDICTION_KEY] = min_diff_model_predictions" as i0_1_0_16
i0_0_0_16 -r-> i0_1_0_16
i0_1_0_16 .u.> mi1_0_16
rectangle #bisque "Model Building and Training" as sa17
sa16 -r-> sa17
rectangle #coral "Model Validation and Assembling" as se0_17
se0_16 -r-> se0_17
se0_17 .u.> sa17
rectangle #cyan "algoFamily=Fairness Metrics\nalgoName=Fairness Indicators\nlibrary=TensorFlow Model Analysis (TFMA)\nfunction=analyze_ raw_ data" as mi0_0_17
mi1_0_16 -r-> mi0_0_17
mi0_0_17 .u.> se0_17
rectangle #pink "min_diff_model_eval_result = tfma.analyze_raw_data(min_diff_model_analysis, eval_config)" as i0_0_0_17
i0_1_0_16 -r-> i0_0_0_17
i0_0_0_17 .u.> mi0_0_17
rectangle #bisque "Visualization" as sa18
sa17 -r-> sa18
rectangle #coral "Visualization" as se0_18
se0_17 -r-> se0_18
se0_18 .u.> sa18
rectangle #cyan "algoFamily=None\nalgoName=None\nlibrary=None\nfunction=print" as mi0_0_18
mi0_0_17 -r-> mi0_0_18
mi0_0_18 .u.> se0_18
rectangle #pink "print('MinDiff Evaluation results: ', evaluation_results)" as i0_0_0_18
i0_0_0_17 -r-> i0_0_0_18
i0_0_0_18 .u.> mi0_0_18
@enduml